In [6]:
import numpy as np
from nets.activations import ReLU

In [34]:
linear = LinearLayer(
    in_dim = 3,
    out_dim = 2,
    act_func = ReLU()
)

linear.weight = np.array([
    [1.2, 0.7, 1, 0.5],
    [0.6, 0.8, 0.4, 0.3]
])

a_prev = np.array([[1.5, 1, 1.25]])

dloss_da = np.array([[0.5, 2]])

In [35]:
linear.forward(a)

array([[4.25, 2.5 ]])

In [36]:
linear.backward(dloss_da, a_prev)

da_ds: [[1. 1.]]


(array([[0.75 , 0.5  , 0.625, 0.5  ],
        [3.   , 2.   , 2.5  , 2.   ]]),
 array([[1.8 , 1.95, 1.3 ]]))