In [1]:
import numpy as np
# from nets.activations import ReLU, Sigmoid 
import nets 

In [3]:
n_nodes = [128, 64, 40 ,16 ,8, 3]
relu = nets.ReLU()
act_func_list = [relu , relu ,relu,relu,relu]
lr = 2.5

mlp = nets.Mahboobeh(n_nodes , act_func_list, lr)

In [2]:
relu = nets.ReLU()
print(relu)

print(relu.forward(np.random.randn(3, 4)))

ReLU
[[0.         0.         0.         0.71226561]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         1.42055537]]


In [3]:
relu = ReLU()
print(relu)

ReLU
[[0.8923231  0.         1.7233012  0.80106932]
 [0.         1.68439575 0.         0.        ]
 [0.         0.         0.         0.51670687]]


In [5]:
relu = Sigmoid()

x = np.random.randn(4, 3)
relu.forward(x)

array([[0.58832094, 0.61166923, 0.18481871],
       [0.25467991, 0.44170914, 0.16721055],
       [0.4646697 , 0.376767  , 0.72606921],
       [0.61913735, 0.2376585 , 0.40221111]])