In [1]:
import numpy as np
from nets import activations

# L2 Loss

In [2]:
class L2Loss:
    def __init__(self) -> None:
        pass
    
    def forward(self,y_out, y_target):
        batch_size = y_out.shape[0]
        return np.sum(
            np.power(y_out-y_target ,2)
        ) / batch_size
    
    def backward(self, y_out , y_target):
        return np.multiply(2, y_out - y_target)
    

# Cross Entropy

In [3]:
class CrossEntropy:
    def __init__(self) -> None:
        pass
    
    def forward(self, y_out , y_target):
        batch_size = y_out.shape[0]
        return np.sum(
            np.multiply(y_target ,np.log(y_out))
        ) / batch_size
        
    def backward(self,y_out , y_target):
        return -np.divide(y_target , y_out)

# SoftmaxCrossEntropy

In [4]:
class SoftmaxCrossEntropy:
    def __init__(self) -> None:
        self.softmax_act = activations.Softmax()
    
    def forward(self, score , y_target):
        y_out = self.softmax_act.forward(score)
        ln_y_out = np.log (y_out)
        loss = - np.sum (np.multiply(y_target,ln_y_out))
        return loss / y_out.shape[0]
    
    def backward(self, score , y_target):
        assert self.check_sum_y_target_one(y_target), "Error!!! Sum of Y_target in every data must equals to one."
        y_out = self.softmax_act.forward(score)
        return y_out - y_target
    
    def check_sum_y_target_one(self, y_target):
        batch_size = y_target.shape[0]
        does_one = np.sum(y_target, axis=1) == np.ones(batch_size)
        return np.sum(does_one) == batch_size
        
        

In [5]:
y_target = np.array([
    [0, 0.5, 0, 0.25, 0.25],
    [1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0]
])

batch_size = y_target.shape[0]
y_target.shape

(3, 5)

In [6]:
np.sum(y_target, axis=1)

array([1., 1., 1.])

In [7]:
np.ones(batch_size)

array([1., 1., 1.])

In [8]:
does_one = np.sum(y_target, axis=1) == np.ones(batch_size)
does_one

array([ True,  True,  True])

In [9]:
np.sum(does_one)

3

In [10]:
np.sum(does_one) == batch_size

True